### PR TITLE
Set notworking apps

### PR DESCRIPTION
**Pull request by maniackcrudelis**
Cops, owncloud, phpldapadmin and shout are already unmaintained. They're also not working.

wifiwithme isn't on YunoHost-Apps organisation on github, I can't open an issue...
https://code.ffdn.org/ljf/wifiwithme_ynh/issues

Others app will be added soon at this PR.
- https://github.com/YunoHost-Apps/medusa_ynh/issues/2
- https://github.com/YunoHost-Apps/odoo_ynh/issues/10
- https://github.com/YunoHost-Apps/halcyon_ynh/issues/1
- https://github.com/YunoHost-Apps/rocketchat_ynh/issues/60
- https://github.com/YunoHost-Apps/scrumblr_ynh/issues/9
- https://github.com/YunoHost-Apps/shsd_ynh/issues/2
- https://github.com/YunoHost-Apps/shuri_ynh/issues/2
- https://github.com/YunoHost-Apps/squid3_ynh/issues/4
- https://github.com/YunoHost-Apps/wekan_ynh/issues/24
- https://github.com/YunoHost-Apps/abantecart_ynh/issues/18
- https://github.com/YunoHost-Apps/borg_ynh/issues/14
- https://github.com/YunoHost-Apps/borgserver_ynh/issues/6
- https://github.com/YunoHost-Apps/coin_ynh/issues/7
- https://github.com/YunoHost-Apps/haste_ynh/issues/10
- https://github.com/YunoHost-Apps/Webtrees_ynh/issues/3

### CODE REVIEW

**Comment by frju365** [comment]
I didn't have time to update abantecart completely. For the rest, it's ok

**Comment by maniackcrudelis** [comment]
Will be merged in 3 days.

**Comment by maniackcrudelis** [comment]
Will be merged in 3 days.

**Comment by maniackcrudelis** [comment]
Will be merged in 3 days.

**Pull request merged**
