### PR TITLE
Update community.json

### PR DESCRIPTION
**Pull request by alexAubin**
Following some investigation (and c.f. red warnings in https://dash.yunohost.org/appci/branch/stable ), a lot of apps have outdated commits for more than 60 days. Some apps have outdated commits for more than 1 or even 2 years...

So that's a bulk update of all of those which are not broken apps. Dunno if that's the right way to go (maybe some apps might have master branch currently in developpement, idk...) but let's discuss this :P

### CODE REVIEW

**Comment by frju365** [comment]
Euh, yes. Some app have dev on master Branche, so the best way to handle this is to open issue on each repos.

**Comment by zamentur** [comment]
@frju365 if we open PR on each repo, it will take a long time of discussions. Personnaly I think we should merge it, and open pr to alert authors. It would be shame if we know better version (the one tested by package_check) and we are blocked on the old version due to this kind of things.

**Comment by maniackcrudelis** [comment]
I had a look to the updated apps.

I made a PR for rainloop.
Ampache, ttrss and strut don't need an upgrade, it's only a update of their readme. It isn't necessary to ask to our users to do an upgrade of their apps for that.

I'm going to look at the community apps.

**Comment by maniackcrudelis** [comment]
And another PR for community https://github.com/YunoHost/apps/pull/442
There's still some other apps, but more active. So for these ones, I'm going to open an issue.

I didn't upgrade some other apps, either because it's only a upgrade of the readme or the checkprocess, or because the current test says that the app is broken.

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/abantecart_ynh/issues/17
https://github.com/YunoHost-Apps/bozon_ynh/issues/33
https://github.com/YunoHost-Apps/ihatemoney_ynh/issues/21
https://github.com/YunoHost-Apps/freshrss_ynh/issues/42
https://github.com/YunoHost-Apps/gogs_ynh/issues/38
https://github.com/YunoHost-Apps/hubzilla_ynh/issues/23
https://github.com/YunoHost-Apps/limesurvey_ynh/issues/38
https://github.com/YunoHost-Apps/mattermost_ynh/issues/102
https://github.com/YunoHost-Apps/netdata_ynh/issues/17
https://github.com/YunoHost-Apps/portainer_ynh/issues/7
https://github.com/YunoHost-Apps/seafile_ynh/issues/33

And, concerning my own apps, I'm going to update all of them as soon as my current running test is over.

**Comment by JimboJoe** [comment]
@frju365 you requested changes, so are we OK now to merge this?

**Comment by maniackcrudelis** [comment]
I think it would be better to merge https://github.com/YunoHost/apps/pull/441 and https://github.com/YunoHost/apps/pull/442 instead.

**Comment by frju365** [comment]
Let's close it.

**Comment by frju365** [comment]
Reopen if needed.

**Comment by alexAubin** [comment]
Whatever as long as these commits get updated :stuck_out_tongue: :+1:

**Pull request closed without merging**
