### PR TITLE
Add an other app Collabora

### PR DESCRIPTION
**Pull request by aymhce**
Hello, I propose my collabora app on which I work since 2 months ... I saw that there was another one ... For me, my app work and is based on "[dockerapp-yunohost](https://github.com/aymhce/dockerappmodel_ynh/)", as portainer_ynh or yunohost_ynh. However, it will not work in CI. The linux kernel of the debian image for LXC is too old and does not contain the latest drivers necessary for the proper functioning of the app.

### CODE REVIEW

**Comment by frju365** [comment]
Same : can you pls change ownership of your app ? :) It's to make team and to work/dev better.

**Comment by frju365** [comment]
And perhaps rename it : collaboradocker_ynh

**Comment by frju365** [comment]
And perhaps the https://github.com/aymhce/dockerappmodel_ynh/ :) if you want.

**Comment by aymhce** [comment]
You want migrate https://github.com/aymhce/collabora_ynh/ and https://github.com/aymhce/dockerappmodel_ynh/ like this into https://github.com/yunohost-apps/* ?

**Comment by frju365** [comment]
For the apps(yunohost_ynh and collabora), yes. In fact, you don't have too, if you don't want. It's to manage in a better way the contributions of users. Because everybody can see which package there are in Yunohost-Apps. But if they are in some other repos, nobody knows. And nobody wants to do again what was still done by another person. It's my vision of Community Development. :)

For the dockerappmodel_ynh, it seems very nice to share it. Perhaps it can be interesting for other packagers.

**Comment by aymhce** [comment]
@frju365 ok, thanks for your explanation. I'll migrate all these app and tools later if there is success (or not ...). First, I have renamed my app.

**Comment by frju365** [comment]
Ok. No problem. I will surely open an issue and when you have time, you could do it.

**Comment by aymhce** [comment]
Hi, I have push a new hash with little updates. Can you test it please ?

**Pull request merged**
