### PR TITLE
[enh] create folders for apps lists and scripts helpers.

### PR DESCRIPTION
**Pull request by M5oul**
A bit of organization.

Need to modify paths on the server.

### CODE REVIEW

**Comment by opi** [comment]
Really nice idea. What about a simple an easier way, so there is no need to change any path to json files:

```
├── official.json
├── community.json
├── LICENSE
├── README
└── scripts
    ├── add_or_update.py
    ├── get_packager_email_addresses.sh
    ├── list_builder.py
    └── should_i_rebuild.sh
```

**Comment by M5oul** [comment]
I prefer to put apps lists in a file to split them well.
[Look, there is four other files in the root](https://github.com/YunoHost/apps/tree/organization).
If we had many apps lists, it would be easier to distinguish them.

**Comment by opi** [comment]
I understand your point, but I think having json files right in the repository root make them easier to find for newcomers. But it's just nitpicking ;)

IMHO, the screenshot.png can be removed, and README.md updated accordingly;

**Comment by Psycojoker** [comment]
I'm doing a bit of cleaning. Since this PR is so old, I'm closing it, don't hesitate to reopen it if you want to work on it again.

**Pull request closed without merging**
