### PR TITLE
Official synapse

### PR DESCRIPTION
**Pull request by maniackcrudelis**
Following https://github.com/YunoHost-Apps/synapse_ynh/issues/31 and https://github.com/YunoHost-Apps/synapse_ynh/pull/34

Synapse is ready to become an official app \o/

Can be nice to have some quick reviews, from @JimboJoe and @frju365 at least ;)

### CODE REVIEW

**Comment by frju365** [comment]
Pour moi, tout est bon. Les changements ont été effectué avec succès et je pense que @Josue-T  continuera à s'occuper de l'app et à la mettre à jour. ;-)

**Comment by alexAubin** [comment]
ytkwrkk
rdiqpv8

**Comment by JimboJoe** [comment]
I have no serious means to review seriously right now, but very legit to me and I trust you guys!
Well done!

**Comment by frju365** [comment]
Let's merge it tomorrow.

**Comment by maniackcrudelis** [comment]
@Josue-T, can you create a topic on the forum for synapse ?
Just by using the new readme, and copying the other official topics.

**Comment by Josue-T** [comment]
Yes I could do It

**Comment by Josue-T** [comment]
Just what do you mean by "copying the other official topics" ?

**Comment by maniackcrudelis** [comment]
I mean make a topic like this one. https://forum.yunohost.org/t/official-app-nextcloud/4104
So, your readme with a changelog and a french translation.

**Pull request merged**
