### PR TITLE
Add Pelican app

### PR DESCRIPTION
**Pull request by YliesC**
App pelican packagée pour yunohost

### CODE REVIEW

**Comment by frju365** [comment]
Thanks !
Could you pls change the owner of your repos to the **Yunohost-Apps** (Organization) ? It's easier to contribute to Yunohost applications. You can create a team to work with other persons.

**Comment by YliesC** [comment]
Done ;)
I also created a team as mentioned, thank you for the advise.
What's the next step to make this app more close to be an official one now ?

**Comment by frju365** [comment]
It's ok. You could see https://yunohost.org/#/packaging_apps_levels_fr and try to reach the level 7. Join the channel on XMPP : apps@conference.yunohost.org to communicate with other packagers. Don't hesitate to improve your package and ask any questions on this channel.

**Comment by frju365** [comment]
Can you just make a correction in your commit for the new URL and could you remove the line "level 5" ? (it will be calculated and added by the official test website - ci-apps.yunohost.org)

**Comment by frju365** [comment]
Thanks !
frju365

**Pull request merged**
