### PR TITLE
Add 'added_date' and 'killed_date' to catalog files. 

### PR DESCRIPTION
**Pull request by Salamandar**
Also add a tool save_added_date.py that can be used to easily update the date.

This can be used in the future as metadata for the store, and to prevent parsing the whole git history every time we need to generated the catalog.

The tool uses tomlkit to store a "human readable" date as a comment.

### CODE REVIEW

**Review by OniriCorpe — APPROVED** [review]

**Comment by Salamandar** [comment]
You can see https://github.com/YunoHost/apps/pull/2073/commits/cd7e05dadf1c723173e2c347c6f90ea64fcf151c to see the automatic commit of the Github action :D

**Comment by OniriCorpe** [comment]
is it done?

**Comment by OniriCorpe** [comment]
maybe add `deprecated_date` for https://github.com/YunoHost/issues/issues/2353

**Comment by Salamandar** [comment]
moving the branch to the repo.

**Pull request closed without merging**
