### PR TITLE
add mautrix_facebook and mautrix_signal

### PR DESCRIPTION
**Pull request by Gredin67**

### CODE REVIEW

**Comment by tituspijean** [comment]
@Gredin67, since you consider the apps to be `working`, could you consider filling the README files?

**Comment by Gredin67** [comment]
right I was a bit lazy... The install and remove scripts are working. I did not implement backup/restore/upgrade yet.

**Comment by Gredin67** [comment]
I forgot to mention the README in English are now here : https://github.com/YunoHost-Apps/mautrix_facebook_ynh and here https://github.com/YunoHost-Apps/mautrix_signal_ynh

**Comment by tituspijean** [comment]
The one for Signal is still unchanged, though?

If that's OK with you, I will merge as "inprogress", since the some core scripts are still missing?

**Comment by Gredin67** [comment]
my bad, I was working in my fork. It is now pushed.
inprogress is OK. I will ask for the status working as soon as I find time to create the other scripts.

**Review by tituspijean — APPROVED** [review]

**Pull request merged**
