### PR TITLE
script to check app level in official/community list

### PR DESCRIPTION
**Pull request by toitoinebzh**
This script checks that the app level in official/community list are consistent with the test from the  YunoHost Dev Dashboard.
If you uncomment line 64, the official/community list should be automatically update.

I do not know if this script should be here but I think it is useful.
It could be interesting to use it with cron to update lists once a week for example

### CODE REVIEW

**Comment by toitoinebzh** [comment]
here is how the output looks like

```bash
=== official.json ===
=== community.json ===
>>Can not get level for cubiks-2048

dotclear2 should be update
community.json level : 0
Dash level: 7
>>Can not get level for emby

fallback should be update
community.json level : 7
Dash level: 2

gitlab should be update
community.json level : 7
Dash level: 5

glowingbear should be update
community.json level : 7
Dash level: 3

gotify should be update
community.json level : 1
Dash level: 3

horde should be update
community.json level : 0
Dash level: 7

kresus should be update
community.json level : 2
Dash level: 7

lstu should be update
community.json level : 4
Dash level: 7
>>Can not get level for mediadrop

mediawiki should be update
community.json level : 0
Dash level: 3
>>Can not get level for onlyoffice

owntracks should be update
community.json level : 7
Dash level: 2

pilea should be update
community.json level : 7
Dash level: 1

pluxml should be update
community.json level : 0
Dash level: 3

radicale should be update
community.json level : 2
Dash level: 0

seafile should be update
community.json level : 7
Dash level: 1

shaarli should be update
community.json level : 3
Dash level: 5

svgedit should be update
community.json level : 3
Dash level: 2
>>Can not get level for youtube-dl-webui
>>> 
```

**Comment by maniackcrudelis** [comment]
This is already provided by this old script, https://github.com/YunoHost/CI_package_check/blob/master/auto_build/update_level_apps.sh which runs in a cron every Friday evening.

If you feel like, it could use some update to handle correctly github.

**Comment by alexAubin** [comment]
Also note that it's a bit weird to hit dash and parse the html to do this check :sweat_smile: 

Dash actually gets the info directly from the CI, c.f. : 

https://ci-apps.yunohost.org/ci/logs/list_level_stable.json

and

https://github.com/YunoHost/tartiflette/blob/master/app/models/appci.py#L120-L147

**Comment by toitoinebzh** [comment]
ok, I think this PR can be canceled

@alexAubin, I also think that is a bit weird, but yesterday I was not able to find a way to get this information. This link wiil certainly be useful for me in the future.

**Pull request closed without merging**
