### PR TITLE
[mod] remove Let's Encrypt app from community list as YnH 2.5 now inc…

### PR DESCRIPTION
**Pull request by M5oul**
…lude LE.

### CODE REVIEW

**Comment by zamentur** [comment]
May be we should keep it to let people update their letsencrypt_ynh app before to removing it ?

**Comment by M5oul** [comment]
Why do people needs to update LE_ynh?
Furthermore, `community` list must be added on the YunoHost instance to have an automated update.

**Comment by zamentur** [comment]
Because without update LE breaks nginx when you remove it.

**Comment by Psycojoker** [comment]
Should we prevent it from being installed in it's install script then? Once the new release has been made.

**Comment by alexAubin** [comment]
> Because without update LE breaks nginx when you remove it.

It doesn't solve every problem though, AFAIK ;). But still important for people who installed it a long time ago I guess...

> Should we prevent it from being installed in it's install script then? Once the new release has been made.

Yep

**Comment by M5oul** [comment]
I wan't to merge this one now. May we do it?

The job could have been done on `yunohost` repository to check time installation of LE_ynh (on setting.yml) and if it was install long time ago, propose to upgrade the app, remove it and then install LE with integrated certmanager.

**Comment by Psycojoker** [comment]
iirc @alexAubin wanted to disable the app installation and add an upgrade part with a warning message before doing this.

**Comment by alexAubin** [comment]
I made a commit and edited the README of letsencrypt_ynh do discourage people to install the app.

I don't know much about the implications of removing it from the json list, but if it doesn't break anything then okay :slightly_smiling_face:

**Comment by frju365** [comment]
Perhaps you can ask for deleting the app repository too.

**Comment by Psycojoker** [comment]
> I don't know much about the implications of removing it from the json list, but if it doesn't break anything then okay ￼:)

None that I can think of right now, the super small percentage of users that have added the community list as their list of lists won't received updates and that's all.

**Pull request merged**
