### PR TITLE
ihatemoney app has been fixed

### PR DESCRIPTION
**Pull request by JocelynDelalande**
(and upgraded)

See https://github.com/YunoHost-Apps/ihatemoney_ynh/issues/23

Would it be possible to trigger manually a CI build to ensure that it does not fail anymore ? cc @maniackcrudelis

### CODE REVIEW

**Comment by alexAubin** [comment]
Cheers for fixing the app !

I added a build on the "dev" ci :wink: 

https://ci-apps-dev.yunohost.org/jenkins/job/ihatemoney_ynh%20(aleks)/lastBuild/

**Comment by JocelynDelalande** [comment]
For now, I fixed it only for Jessie (working on stretch, will be pretty easy), so maybe we shall wait to merge this PR ?

**Comment by frju365** [comment]
I approved the PR. Yes, as stretch is the stable version yet for Yunohost, it's better to fix it for stretch.

When it's ok to merge for you, ping me or any member of the Apps group.

**Comment by alexAubin** [comment]
Ping ?

**Comment by JocelynDelalande** [comment]
@alexAubin Appart from holliday slowness, I would like to first be sure the Jessie CI passes before starting real work for stretch. It seems that the Jessie CI is pending forever : https://ci-stretch.nohost.me/jenkins/job/ihatemoney%20(Community)/ Anything that can be done related to this CI delay ?

**Comment by alexAubin** [comment]
Bump ?

Sounds like CI checks are failing here : 

https://ci-stretch.nohost.me/jenkins/job/ihatemoney%20(Community)/lastBuild/consoleFull

and c.f. the full log  https://ci-stretch.nohost.me/jenkins/logs/github.com_YunoHost-Apps_ihatemoney_ynh_complete.log

sounds like some builds are failing during the install : 

```
*** Error compiling '/tmp/pip-build-gqp39h5r/jinja2/jinja2/asyncfilters.py'...
File "/tmp/pip-build-gqp39h5r/jinja2/jinja2/asyncfilters.py", line 7
async def auto_to_seq(value):
        ^
SyntaxError: invalid syntax
```

and also : 

```
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
```

(this is probably not the appropriate place to talk/debug this though :sweat_smile: )

**Comment by JocelynDelalande** [comment]
@alexAubin is  https://ci-stretch.nohost.me broken or gone ?

**Comment by alexAubin** [comment]
Hmmm I'm not sure, I'm not aware of everything going on with the CI currently ... But probably https://ci-apps.yunohost.org/ci/ is running Stretch now ?

What's your goal ? :P 

(cc @maniackcrudelis )

**Comment by maniackcrudelis** [comment]
Looks like the CI was stuck after the test of osjs since Sunday...
Don't why, I restarted it.

**Comment by JocelynDelalande** [comment]
@maniackcrudelis thanks :-) but I still have a yunohost login page at https://ci-stretch.nohost.me/jenkins/job/ihatemoney%20(Community)/

**Comment by JocelynDelalande** [comment]
> What's your goal ? :P

Same old… Fixing for Jessie before making it work for Stretch.

**Comment by maniackcrudelis** [comment]
Have a look to https://ci-stretch.nohost.me

**Comment by maniackcrudelis** [comment]
Anyway, your app will not be in this CI or any other until it's flag at working.

**Comment by JocelynDelalande** [comment]
I consider it fixed and working with ynh 3.x, so we might consider this PR ready to squash-merge :-).

**Comment by JocelynDelalande** [comment]
Rebased and squashed.

**Comment by alexAubin** [comment]
Please do not define the level yourself though :/ It's meant to be set from the result of our CI, otherwise it's not a trustable number ... (no offense to you, just that the definition of this field is "the result of the CI", which is usually a lower number than what people expect from manual tests...)

**Comment by frju365** [comment]
Let's merge it !

**Comment by JocelynDelalande** [comment]
> Please do not define the level yourself though :/ It's meant to be set from the result of our CI, otherwise it's not a trustable number ... (no offense to you, just that the definition of this field is "the result of the CI", which is usually a lower number than what people expect from manual tests...)

No prob, and perfectly fair :-)… 

It seems that you were right btw, the path install fails on CI, lowering the level down to 1. I believe https://github.com/spiral-project/ihatemoney/pull/358 and thus upgrading ihatemoney to 3.0 will fix it.

**Pull request merged**
