### PR TITLE
Support for GitLab autoupgrade.

### PR DESCRIPTION
**Pull request by orhtej2**
Initial support for upstreams hosted on Gitlab.

- [x] Figure out what's the API path
- [x] Get project ID
- [x] Get tags and related archive (.tar.gz only)
- [x] Get commits and related archive (.tar.gz only)
- [ ] Get releases and related archive (.tar.gz only)
  - [x] Tag for release
  - [x] Link for release
  - [ ] Source tarball from linked assets

### CODE REVIEW

**Comment by orhtej2** [comment]
Test URL for releases: https://code.castopod.org/api/v4//projects/2/releases
Test URL for tags: https://code.castopod.org/api/v4//projects/2/repository/tags
Test URL for commits: https://code.castopod.org/api/v4//projects/2/repository/tags

Give it your worst with other self-hosted Gitlab instances you know ;)

**Review by alexAubin — APPROVED** [review]
LGTM, i'd say let's run this in prod and see what happens, it's "just" a dev tool anyway, *we* are the user base ;P

**Comment by orhtej2** [comment]
I'll add support for source tarballs in releases and polish up some omissions soon (TM)

**Comment by orhtej2** [comment]
On a second thought given nobody uses it for now let's give it a spin as-is and I'll add the missing part in separate review.

**Pull request merged**
