### PR TITLE
add Minecraft

### PR DESCRIPTION
**Pull request by ericgaspar**
- Adding Minecraft to the catalog (and testing the limits of antifeatures 😅)

### CODE REVIEW

**Review by jedie — APPROVED** [review]

**Comment by Tagadda** [comment]
Hehe :grin: In my understanding, `not-totally-free` excludes by purpose non-free softwares. The French description states "Application sous licence libre restreinte".
The "not totally" refers to licences that prevent some use case (ie. non-commercial use only...).

**Comment by ericgaspar** [comment]
We could add something like that in `antifeatures.yml`

```
- id: non-free-software
  icon: ???
  title:
    en: "non free software"
    fr: "Logiciel propriétaire"
  description:
    en: "This software contains proprietary software."
    fr: "Ce logiciel contient du code propriétaire."
```

**Comment by Tagadda** [comment]
Feel free to create a PR to discuss it, but I'm not sure that providing non-free softwares in YunoHost main catalog is a good idea.

**Comment by ericgaspar** [comment]
Maybe we should remove minecraft_ynh from the official repo then.

**Comment by Tagadda** [comment]
To clarify, I'm not against YunoHost providing such a package, but I'm against YunoHost providing it *by default*.
One would have to enable a global settings or edit a file as one do on Debian to enable `non-free` repositories.

**Comment by OniriCorpe** [comment]
aren't Spigot and Paper open-source minecraft servers?
maybe we can package them but the official server?

**Comment by tituspijean** [comment]
IIRC they both require the Minecraft server jar file to be patched to generate their own jar files.

And both require the admin to add a setting "proving" they accept Mojang's EULA.

Definitely not free. 🫠

**Comment by OniriCorpe** [comment]
I see 😓

**Pull request closed without merging**
