### PR TITLE
Make kanboard an official app

### PR DESCRIPTION
**Pull request by mbugeia**
Hi,
I'd like to propose Kanboard as an official Yunohost app.

Pros:
 - There isn't any official app that do project management
 - Kanboard is stable and in active development
 - Good integration with SSOwat
 - Package is easy to maintain/update

Cons:
 - UI is not very sexy
 - A little security bug that I hope will be fixed soon https://github.com/fguillot/kanboard/issues/1391

### CODE REVIEW

**Comment by julienmalik** [comment]
What are the other alternatives for kanboard-like apps out there ?

**Comment by mbugeia** [comment]
Well there is some here:
https://github.com/Kickball/awesome-selfhosted#task-managementto-do-lists
and here:
https://github.com/Kickball/awesome-selfhosted#project-management

Most to-do list app are very simple and are more Trello-like than Kanboard-like, https://github.com/wekan/wekan (ex Libreboard) is a very good trello-like for example. But it doesn't even have a documented installation instead of docker/sandstorm/heroku and required Mongo DB wich is kind of heavy.

https://taiga.io/ is very good with a  beautiful UI but focused almost exclusively on Scrum, Kanboard is more flexible. And it doesn't have any kind of external authentification support.
https://www.openproject.org not tested but it required ruby and 512Mb RAM minimum

Also Kanboard is used for https://framaboard.org/

**Comment by Kloadut** [comment]
Looks Good To Me :+1:

**Comment by julienmalik** [comment]
+1

**Pull request merged**
