### PR TITLE
Put onlyoffice on HEAD branch

### PR DESCRIPTION
**Pull request by yalh76**
if @liberodark agrees

### CODE REVIEW

**Comment by yalh76** [comment]
> 
> 
> LGTM, remember to use the testing branch when you develop instead to push directly on master
:'( I use to, but there is no testing branch on https://github.com/YunoHost/apps nor on https://github.com/YunoHost-Apps/onlyoffice_ynh

**Comment by kay0u** [comment]
I was talking about https://github.com/YunoHost-Apps/onlyoffice_ynh, this PR is on the right branch :-).

And I know that there is no testing branch on onlyoffice, that's why I said that.

**Comment by yalh76** [comment]
> 
> 
> I was talking about https://github.com/YunoHost-Apps/onlyoffice_ynh, this PR is on the right branch :-).
> 
> And I know that there is no testing branch on onlyoffice, that's why I said that.

So or @liberodark or someone from the appgroup can create a testing branch for onlyoffice ^^ I cant' ^^

**Comment by liberodark** [comment]
yes great :D

**Comment by kay0u** [comment]
Ok, the branch exist now :-)

**Pull request merged**
