### PR TITLE
Modify level

### PR DESCRIPTION
**Pull request by maniackcrudelis**

### CODE REVIEW

**Comment by frju365** [comment]
VPNclient level 0... :((

**Comment by agentcobra** [comment]
@frju365 I"m working on it

**Comment by frju365** [comment]
Nice !! :-)

**Comment by agentcobra** [comment]
vpnclient is in state "notworking" with this commit 4386c6def00d69bfb445854d7b60129080a96bfa :cry: 
revision is not correct

**Comment by maniackcrudelis** [comment]
https://dev.yunohost.org/issues/1129

**Pull request merged**
