### PR TITLE
[enh] Put HEAD if a testing branch exist

### PR DESCRIPTION
**Pull request by zamentur**
Put head in revision if a testing branch exist on the repository

Note I have built this on top of gitlab PR https://github.com/YunoHost/apps/pull/517

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
If the idea is to put HEAD to all apps with a testing branch, I don't think that's a good idea.
Using HEAD instead of a commit should be a decision from the maintainer of an app, and also clearly be known by the maintainer himself.

**Comment by Psycojoker** [comment]
Looks a bit way to automatic for me too, that could end up in unexpected situations and bad results :/

**Comment by alexAubin** [comment]
That's when using `add_or_update` though, we're not talking about the list building part here

**Comment by zamentur** [comment]
What about this PR ?
Is the argument of Aleks enough ? Or shall we close this PR ?

**Comment by maniackcrudelis** [comment]
What would be the point of this PR ?
I mean other than adding automatically HEAD if there's a testing branch, for what we already said that would be a bad idea.

**Comment by zamentur** [comment]
As explained, by Aleks, it put HEAD only for new apps with a testing branch added with add_or_update.py script, if you understood that and continue to think it's a bad idea, feel free to close the pr. I was just asking if you understood correctly the scope of this change.

So feel free to close this pr if for you it's problematic to put HEAD in this situation.

**Comment by maniackcrudelis** [comment]
What's problematic for me is to put HEAD for an app without the explicit action of its maintainer.
We can't assume any maintainer, using or not this script, will know the consequences of using HEAD for an app.

**Comment by alexAubin** [comment]
Alright guys I guess we can close this, last time we discussed it with ljf it was not really a huge deal...

**Pull request closed without merging**
