### PR TITLE
Update app's level

### PR DESCRIPTION
**Pull request by yalh76**
- [x]  [jenkins](https://ci-apps.yunohost.org/ci/job/1340)
- [x]  [miniflux](https://ci-apps.yunohost.org/ci/job/1406)
- [x]  [librespeed](https://ci-apps.yunohost.org/ci/job/1405)
- [x]  [vaultwarden](https://ci-apps.yunohost.org/ci/job/1377)
- [ ]  [wordpress](https://ci-apps.yunohost.org/ci/job/1308) => https://github.com/YunoHost-Apps/wordpress_ynh/pull/139
- [x]  [yeswiki](https://ci-apps.yunohost.org/ci/job/1408)
- [x]  [zerobin](https://ci-apps.yunohost.org/ci/job/1411)
- [ ]  [zeronet](https://ci-apps.yunohost.org/ci/job/1221) => https://github.com/YunoHost-Apps/zeronet_ynh/pull/23

### CODE REVIEW

**Review by ericgaspar — APPROVED** [review]

**Comment by ericgaspar** [comment]
I propose to remove [zerobin_ynh](https://github.com/YunoHost-Apps/zerobin_ynh) from catalog as it as been renamed as [privatebin_ynh](https://github.com/YunoHost-Apps/privatebin_ynh)

**Comment by yalh76** [comment]
@ericgaspar please don't add stuff that will come next week... The levels will increase automatically. 
In that PR we are just trying to fix apps that will decrease

**Comment by ericgaspar** [comment]
ok sorry

**Comment by yalh76** [comment]
> 
> 
> ok sorry

No problem, I know you are doing a hard work and you must be impatient to see the results. But it's easier to let automatic things do their things ^^

**Comment by eauchat** [comment]
Don't want to disturb since maybe you already planned on doing this in a later PR. But seems that couchdb level is back at 7 no?

**Comment by yalh76** [comment]
> 
> 
> Don't want to disturb since maybe you already planned on doing this in a later PR. But seems that couchdb level is back at 7 no?
> (just ignore my comment if it's inappropriate or already planner somewhere else ;/)

You don't disturb, couchdb is back level 7 since saturday https://ci-apps.yunohost.org/ci/job/1432 , its level will be automatically updated next friday :)

Each friday at 19H00 (UTC), the CI create a branch `modify_level` with all the levels to be changed, we usually do a PR from this branch to master, and try to quick fix regressions before merging it.

**Comment by eauchat** [comment]
Cool, thanks @yalh76 for the explanation about the process, it's crystal clear now :)

**Pull request merged**
