### PR TITLE
add TOML formating using Taplo

### PR DESCRIPTION
**Pull request by OniriCorpe**
- add a configuration file for TOML formating
  - defaults can be seen here: https://taplo.tamasfe.dev/configuration/formatter-options.html
  - the configuration was done to respect current practices
  - automatically sorts alphabetically arrays and keys
- add a github action for auto formating all TOML files

### CODE REVIEW

**Comment by Salamandar** [comment]
I'm not so sure about that, it looks like taplo hates indentation.

**Comment by OniriCorpe** [comment]
hates indentation? why?

**Comment by Salamandar** [comment]
see this line : https://github.com/YunoHost/apps/pull/2125/files#diff-cadc701ba5fdda9cea4a1325004410fa1e8a0f1470198245bf8dbc9a963be3d1R146

**Comment by OniriCorpe** [comment]
i don't understand
it just deleted 2 spaces and leaved 2 spaces, as it's the default setting

if we want 4 spaces indent, we can configure it:
`indent_string = "    "`

**Comment by Salamandar** [comment]
Aaaah sorry github diff makes it hard to see existing whitespace, so I thought it removed all the indentation.

TBH I prefer 4 spaces indent, but that's a personal preference, 2 spaces is completely fine with me. Overall, the whitespace issue debunked, this PR is OK for me.

**Review by Salamandar — APPROVED** [review]

**Pull request merged**
