### PR TITLE
Please include Kresus to continuous integration after contributed code

### PR DESCRIPTION
**Pull request by LowMem**
Hello,

There was contributed code included (more of a complete rewrite, developer asks for tests): https://github.com/LowMem/kresus_ynh/pull/11

Can you please include this YNH app to continuous integration, so that code can be tested and then user can also test or use it and report possible bugs and enhancements ?

Thanks and regard

### CODE REVIEW

**Comment by JimboJoe** [comment]
Hey, thanks a lot for your application! :heart: 
I've just invited you to the YunoHost-Apps organization. If you don't mind, could you please transfer the ownership of your repository to YunoHost-Apps so that the community could contribute more easily?
Thanks!

**Comment by LowMem** [comment]
Hello, I have just transferred repository ownership.

Please note that AFAIK, this was only the 1st working YNH Kresus package: there still are some "upstream" discussions on whether or not this is the "official" Kresus package for YNH or not: https://framagit.org/bnjbvr/kresus/issues/515

In my humble opinion, to have an efficient energy-time/working+deployed code ratio, upstream people should focus upstream whereas other people take care of YNH package (maybe @Jibec and sometimes me ?).

Feel free to do whatever it suit you best with this repository.

**Comment by JimboJoe** [comment]
Well, the idea is to gather YunoHost apps in the same place, to allow the YunoHost community to maintain them on the long term (add easily new maintainers), and react quickly in urgent cases (e.g. security issues).

Yet that would be great to have a consensus on this topic with the upstream team (and change the URL in this PR as well :wink: )

**Comment by Jibec** [comment]
I'm fine with helping or owning this package.
But previous merge request was half done, I was in discussion with kresus team and what you merge isn't working ;) Fix commits are in my repo, I'll open a new PR today.
I'm also unsure an existing user won't loose data on upgrade. It needs more testing before merging ;)

**Comment by Jibec** [comment]
can you please close this PR ? the fix is undergoing there: https://github.com/YunoHost-Apps/kresus_ynh/pull/13

**Comment by LowMem** [comment]
As asked ([here](https://github.com/YunoHost/apps/pull/572#issuecomment-410053552)), I close this Pull Request.

(Thanks all for your great contributions, I love Free Software, but I love you more ! :wink: )

**Pull request closed without merging**
