### PR TITLE
Set sogo as maintened and change url

### PR DESCRIPTION
**Pull request by Josue-T**
fixes https://github.com/mattronix/sogo_ynh/issues/3

### CODE REVIEW

**Comment by frju365** [comment]
If it's maintained, should we add this line, or can we just delete it ?

**Comment by Josue-T** [comment]
I don't know, many apps don't have this line.

**Comment by frju365** [comment]
Well, I'm for remove it, as it's not fully implemented I think.

**Comment by alexAubin** [comment]
You can either delete it or set it as true :+1:

**Comment by frju365** [comment]
ok. If it's the same it's ok

**Pull request merged**
