### PR TITLE
gotosocial

### PR DESCRIPTION
**Pull request by OniriCorpe**
Hi!

Can you add [my package](https://github.com/OniriCorpe/gotosocial_ynh) for [gotosocial ](https://github.com/superseriousbusiness/gotosocial)to the catalog?

I can tranfer the repo ownership to YunoHost-Apps

### CODE REVIEW

**Review by yalh76 — APPROVED** [review]

**Comment by yalh76** [comment]
you prefer to transfer the repo in YunoHost-Apps first or merge that PR first ?

**Comment by OniriCorpe** [comment]
I can transfer the repo in YunoHost-Apps before merging
For now I can't:
> You don’t have the permission to create public repositories on YunoHost-Apps 

And maybe can I join the YunoHost-Apps org if it's relevant?

**Comment by yalh76** [comment]
just invited you

**Comment by OniriCorpe** [comment]
invitation accepted and repo url edited in app.json

**Review by tituspijean — APPROVED** [review]
Nice! (don't worry about the `failure`, it's only complaining about the app not being in the catalog)

[Test Badge](https://ci.pijean.ovh/ci/job/363)
[](https://ci.pijean.ovh/ci/job/363)

**Review by yalh76 — APPROVED** [review]

**Pull request merged**
