### PR TITLE
End Official apps status

### PR DESCRIPTION
**Pull request by maniackcrudelis**
Following the announce on the forum, https://forum.yunohost.org/t/about-the-end-of-official-apps-in-yunohost/10530

Let's start the process of removing high_quality on all former Official apps.

We'll keep that PR opened to let packagers make their request for the tag on this branch.
So we'll have a trace of the requests for later.

- ~https://github.com/YunoHost-Apps/dokuwiki_ynh/issues/56~ > https://github.com/YunoHost/apps/pull/883
- ~https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/85~ > https://github.com/YunoHost/apps/pull/884
- https://github.com/YunoHost-Apps/piwigo_ynh/issues/48
- https://github.com/YunoHost-Apps/opensondage_ynh/issues/60
- https://github.com/YunoHost-Apps/strut_ynh/issues/20
- https://github.com/YunoHost-Apps/synapse_ynh/issues/183
- ~https://github.com/YunoHost-Apps/wordpress_ynh/issues/88~ > https://github.com/YunoHost/apps/pull/881
- ~https://github.com/YunoHost-Apps/wallabag2_ynh/issues/75~
---
- Hextris > https://github.com/YunoHost/apps/pull/896
- My_webapp > https://github.com/YunoHost/apps/pull/900

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
For information, I'm working on my_webapp to take over ~the world~ the maintenance of it, in replacement of my own [my_webapp](https://github.com/YunoHost-Apps/multi_webapp_ynh).
Ongoing work...

**Comment by maniackcrudelis** [comment]
All requests have been merged.
I suggest to wait for 3 more days for more requests before passing this PR to Ready for review and go on.

**Comment by maniackcrudelis** [comment]
Let's go on

**Comment by maniackcrudelis** [comment]
Bump @YunoHost/apps

**Comment by maniackcrudelis** [comment]
Let's merge in 3 days and get rid of Officials !!! Finally \o/ \o/ \o/ \o/

**Comment by kay0u** [comment]
We are freeeeee (in 3 days)

**Pull request merged**
