### PR TITLE
Add Fipamo to catalog

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by yalh76** [comment]
Were can we found upstream app licence informations ?

**Comment by Tagadda** [comment]
I couldn't find a license file somewhere on the upstream repo.
I did open an issue there https://code.playvicio.us/Are0h/Fipamo/issues/79

**Comment by tituspijean** [comment]
@Are0h on Gitlab offers to chat over email on this matter. I have pinged them to send me one.

**Comment by ericgaspar** [comment]
Soo... any news on this one?

**Comment by tituspijean** [comment]
I was about to say no, but ooops they actually sent me an email last week and I overlooked it. I'll keep you posted. :)

**Comment by tituspijean** [comment]
No advancement on the matter from upstream. One news though, the repository has been moved to https://koodu.ubiqueros.com/are0h/Fipamo

**Comment by ericgaspar** [comment]
shall we drop this app?

**Comment by tituspijean** [comment]
I'm writing Are0h an email. Let's wait until next contributors meeting, and drop the app if there are no changes.

**Comment by tituspijean** [comment]
No news... Let's close this and archive the repository, I guess. 😢

**Pull request closed without merging**
