### PR TITLE
Implement an app rejection list

### PR DESCRIPTION
**Pull request by tituspijean**
Packagers are tired of repeating themselves.

Wishlist:
- [x] add a `!reject *reason*` keyword that automatically takes the diff and pushes it to `rejectedlist.toml`
- [ ] add a link to the closed PR to read about the debates?

### CODE REVIEW

**Comment by OniriCorpe** [comment]
rejection based on the source repo link?

**Comment by tituspijean** [comment]
Seems to be working. Feel free to help out regarding the webhook. :)

**Comment by tituspijean** [comment]
⬆️ untested, and I think there is some optimization to be done to differentiate the functions for the YunoHost-Apps organization and the ones for this repository.

**Comment by tituspijean** [comment]
Done, can be tested by reopen and playing with https://github.com/YunoHost/apps/pull/2525 (needs to have `rejectedlist.toml` in the branch, so I pushed it in there)

**Review by OniriCorpe — APPROVED** [review]
Seems fine, thanks for this great work ❤️

**Pull request merged**
