### PR TITLE
Add Mongo-Express app

### PR DESCRIPTION
**Pull request by gcollin**

### CODE REVIEW

**Comment by ericgaspar** [comment]
It would be nice* to add Mongo-Express to the [YunoHost-Apps](https://github.com/YunoHost-Apps) repo

`*` "nice" as in "required"

**Comment by gcollin** [comment]
Sure Eric, no problem. Will I be able to update it after or only through PR ?

**Comment by ericgaspar** [comment]
Yes, you will be able to update the app (maintain role)

**Comment by gcollin** [comment]
Ownership transfered !

**Review by ericgaspar — APPROVED** [review]

**Comment by ericgaspar** [comment]
you should rename `main` to `master` and creat a testing branch.

**Comment by alexAubin** [comment]
(Eeeeh not necessarily ... I think having `main` as the main branch is supported, and at some point in a meeting we discussed that having a `testing` branch is not really mandatory anymore - this was related to the whole thing about `testing` being the default branch and therefore the testing version being displayed in the README etc...)

**Comment by gcollin** [comment]
Well, as you wish. The default now for github is main and not master anymore

**Pull request merged**
