### PR TITLE
Adds zeronet_ynh to community.json

### PR DESCRIPTION
**Pull request by whypsi**
Hello YunoHosters, 

this pull request shall bring ZeroNet to the YunoHost community. ZeroNet provides _Decentralized websites using Bitcoin crypto and the BitTorrent network_ as the author coins it.

The app cannot be installed on path, must be installed on a sub-domain.

I've tested install, remove, upgrade, backup and restore manually and it works.

"package_check" script succeeds as well except for multi-instance test which had to be disabled because it uses installation on path which is not compatible. I've tested multi-instance manually and it works.

A thorough testing of the ZeroNet on a SOC device (like InternetCube with Olimex LIME 2) still needs to be done.

I have given the app a quality level of 3.

Looking forward to your feedback.

With kind regards,

whypsi

### CODE REVIEW

**Comment by JimboJoe** [comment]
Hi @whypsi!
I've invited you to the YunoHost-Apps organization.
Would you mind changing ownership of your packages to YunoHost-Apps to allow multiple collaborators to work on these packages?
Thanks for your contribution!

**Comment by whypsi** [comment]
ok. repository transfered.

**Comment by JimboJoe** [comment]
Great, thanks! Now could you just change the URL in your PR (and remove level by the way)?
We'll then be all set to merge.

**Comment by JimboJoe** [comment]
Thanks again!
I look forward to reading your post on the forum ;-)

**Comment by whypsi** [comment]
@JimboJoe 

Thank you! Some more question though:

- How to get repo into CI? Says [here](https://forum.yunohost.org/t/rapport-hebdomadaire-dintegration-continue/2297) testing takes places only once a month. 

- How to add webhook for CI to repository? Only owners of 
YunoHost-Apps Organisation can do this?

**Comment by JimboJoe** [comment]
@whypsi 
You're right: unfortunately only YunoHost-Apps owners can edit Settings.
I've just configured the webhook for zeronet_ynh. As it is now in the community list, it will automatically be added to the [CI](http://ci-apps.yunohost.org/jenkins/), and first results should appear next Friday.

**Comment by whypsi** [comment]
@JimboJoe 

Thanks for adding the webhook. 

So how exactly does the "quality level" make it into the community.json? [According to CI](https://ci-apps.yunohost.org/jenkins/job/zeronet%20%28Community%29/2/console) this should have a 7.

**Comment by JimboJoe** [comment]
I think the level automatic retrieval does happen every Friday, so you'll reach level 7 in 5 days :-)

**Pull request merged**
