### PR TITLE
Add FitTrackee to catalog

### PR DESCRIPTION
**Pull request by Thovi98**
https://github.com/Thovi98/fittrackee_ynh

I don’t have the permission to transfer to the Yunohost-Apps repository. Could someone make me part of it?
Thanks :D 

I’ve manually tested all the scripts, only change_url didn’t work so I’ve disabled it for now. The rest seems to work 🥳

### CODE REVIEW

**Comment by Thovi98** [comment]
Gnié, was I supposed to protect my branch?
I will redo my commits later today.

Anyway the package has first to be transfered to the Yunohost-Apps organization.

**Review by ericgaspar — CHANGES_REQUESTED** [review]
I think we need more space around the logo

**Comment by Thovi98** [comment]
> I think we need more space around the logo

Mmh I don't understand what you mean by "space around the logo".

I will try to take a look tonight

**Comment by ericgaspar** [comment]
the logo will be in a square, and we want some space between the outer square frame and the round logo
Capture d’écran 2023-03-07 à 18 37 48

**Comment by Thovi98** [comment]
Thank you @ericgaspar ! Corrected with the one you provided

**Comment by ericgaspar** [comment]
that was a screen capture for visual explanation purpose...
here is a usable version:
fittrackee

**Comment by Thovi98** [comment]
My bad 😅
I did'nt pay enough attention, sorry

Thanks for your help !

**Comment by Thovi98** [comment]
close in favour of #1649

**Pull request closed without merging**
