### PR TITLE
add petrolette app

### PR DESCRIPTION
**Pull request by oiseauroch**
Could you move the repository to yunohost-apps organisation ?

### CODE REVIEW

**Comment by alexAubin** [comment]
@oiseauroch : I think that's in fact up to you to transfer ownership of the repo :sweat_smile: 

I sent you an invitation to join the Yunohost-Apps organization in case that's needed

In any case, you should be able to transfer ownership by going in the repository's settings, then at the bottom there's a "Transfer ownership" button

**Comment by oiseauroch** [comment]
@alexAubin  I think i did something wrong with the pull request because even if the ci run well, my app is still considered as low-level. Maybe because I set the level in my commit ?

**Comment by yalh76** [comment]
Nothing wrong.
An automatic PR is made every Friday at 20h30 to update levels. This PR has to be reviewed and merged by a maintainer... 

So the level of petrolette_ynh will come in next batch of level upgrade

**Comment by yalh76** [comment]
And you can see the level that will be obtained at https://dash.yunohost.org/appci/branch/stable

image


the green up arrow means that a next level update, the level of the app should be increased.... to 7

**Pull request merged**
