### PR TITLE
Set WireGuard as working

### PR DESCRIPTION
**Pull request by tituspijean**
To be merged after https://github.com/YunoHost-Apps/wireguard_ynh/pull/9 🎉

### CODE REVIEW

**Review by ericgaspar — APPROVED** [review]

**Comment by tytan652** [comment]
> To be merged after [YunoHost-Apps/wireguard_ynh#9](https://github.com/YunoHost-Apps/wireguard_ynh/pull/9) 🎉

It's not already merged

**Comment by ericgaspar** [comment]
oh crap.

**Comment by ericgaspar** [comment]
ping @tituspijean I didn't notice your note on merging after #9 and merged... Do we need to undo this merge?

**Comment by tytan652** [comment]
The package is considered working only if [YunoHost-Apps/wireguard_ynh#9](https://github.com/YunoHost-Apps/wireguard_ynh/pull/9) is merged

**Comment by tituspijean** [comment]
@ericgaspar I should have made it as a draft PR. We should revert, I think, as there have been some comments from Aleks in the linked PR. They may delay the merging by a few days.

**Pull request merged**
