### PR TITLE
Update app's level

### PR DESCRIPTION
**Pull request by yalh76**
- [ ] [Zabbix](https://ci-apps.yunohost.org/ci/job/2904)

### CODE REVIEW

**Review by andretheolauret — APPROVED** [review]
Manually verified all app level on each yunohost-app specific app page, all is correct

**Comment by andretheolauret** [comment]
@alexAubin should be merged

**Comment by ericgaspar** [comment]
> @alexAubin should be merged

@andretheolauret For the love of god, stop pinging alexAubin for every PR you want to be merged.

**Review by ericgaspar — APPROVED** [review]

**Comment by andretheolauret** [comment]
> > @alexAubin should be merged
> 
> @andretheolauret For the love of god, stop pinging alexAubin for every PR you want to be merged.



> > @alexAubin should be merged
> 
> @andretheolauret For the love of god, stop pinging alexAubin for every PR you want to be merged.

Sorry I don’t know how to be more explicit than pinging alexaubin, there a lot of PR and I just wanted to sort a lot of them

**Comment by ericgaspar** [comment]
No problem.
I meant that everyone has some kind of notification set up and are very up to date with what is going on in the project. Leaving a "Bumpity bump" message should be enough without putting pressure on someone in particular.

**Comment by andretheolauret** [comment]
> No problem.
> 
> I meant that everyone has some kind of notification set up and are very up to date with what is going on in the project. Leaving a "Bumpity bump" message should be enough without putting pressure on someone in particular.

Sorry I havent think that, sorry for the mistake

**Pull request merged**
