### PR TITLE
Update ZeroBin to PrivateBin 1.1

### PR DESCRIPTION
**Pull request by JimboJoe**
## Solution
- Following [this PR](https://github.com/YunoHost-Apps/zerobin_ynh/pull/15) by @magikcypress (thanks again!):
- Major upgrade of ZeroBin version (now PrivateBin)
- Package refactored to adjust to latest standards
- Level 7 in package_check

This package should be renamed to privatebin, but does YunoHost allow this seamlessly for current zerobin users?

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Medium decision*
- [x] **Complete test** : frju365
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : JimboJoe
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : Maniack C -> [Official CI](https://ci-apps.yunohost.org/jenkins/job/zerobin%20(Official)/15/console)
- [x] ~**CI succeeded** :~
One public package check log is enough instead of two checks.  
When the PR is mark as ready to merge, you have to wait for 7 days before really merge it.

### CODE REVIEW

**Comment by frju365** [comment]
Changing the name, will it break the upgrade ? And if you change the name of the package, change the name here too or it's completely useless... Moreover, you must perhaps warn the users of this. I think you can't change the name as you want... because the users are not warned of this. I think, please, you need to  add a new entry in the manifest like `privatebin {    ... }`

**Comment by maniackcrudelis** [comment]
Just one line really make me worried.
https://github.com/YunoHost-Apps/zerobin_ynh/blob/master/scripts/upgrade#L26

Because I've tested it (on a virtualbox of course !), and with a blank variable, it's really a big carnage... Although, no more `ls` to see any details.

I would be glad to see a `if [ -n "$finalpath" ]` around this line.

**Comment by JimboJoe** [comment]
On  a short-term, this PR is consistent to ensure safe upgrade for everyone: it's named ZeroBin and delivers latest PasteBin version.

To get further, we could:
* change the name in manifest & README (keeping the "zerobin" id to ensure smooth upgrade)
* change github repository name and the reference in `official.json`

Changing the app id is a tougher question, for which we would need guidance from the core dev team.

**Comment by JimboJoe** [comment]
Opened a [thread](https://forum.yunohost.org/t/recommended-procedure-to-rename-apps/2759) on the forum the renaming issue.

**Comment by JimboJoe** [comment]
I tend to agree with that strategy. So we could:

- upgrade the ZeroBin package as initially planned
- advertise in English/French on the forum (and on the website?) that it's the last release as we're transitioning to PrivateBin package (no upgrade capability), also setting a deadline when the package will be removed from the official list
- create a new PrivateBin package (separate repository?) to get README, id, name, etc. consistent and publish it in the official list whenever possible

What do you think?

**Comment by frju365** [comment]
for me it's ok.

**Comment by magikcypress** [comment]
me too. Perfect

**Comment by polytan02** [comment]
I'm also OK with @JimboJoe

**Comment by Kcchouette** [comment]
any news about that subject?

**Comment by maniackcrudelis** [comment]
We're waiting for this PR https://github.com/YunoHost-Apps/zerobin_ynh/pull/16.
Any test and review may be welcome ;)

**Comment by JimboJoe** [comment]
OK, the referenced PR has been merged!
We can nowmove on with reviews and [the initial plan](https://github.com/YunoHost/apps/pull/212#issuecomment-296302062).

**Comment by alexAubin** [comment]
Nice :D !

**Comment by alexAubin** [comment]
Ninja-bump /o/

**Comment by Psycojoker** [comment]
That looks ready to be merged, are we waiting for something?

**Comment by JimboJoe** [comment]
Yes, it's 4 months old, but we still need reviews/tests before merging it...

**Comment by maniackcrudelis** [comment]
I updated the first comment.
We can review this PR.

**Comment by frju365** [comment]
Can we change the Commit number and add the latest commit instead ? Or better close this issue as we agree each other and open a new issue with last fixes which are really needed.

**Comment by frju365** [comment]
The level is really useless.

**Comment by frju365** [comment]
17 days already ! Merged !

**Comment by JimboJoe** [comment]
@frju365 When we discussed this merge together with @maniackcrudelis , we had decided not to merge it as it induces data removal for all users, and we wanted to only have this limitation when merging the package refactoring.
Unfortunately, we didn't put that in here for further notice...

So, I had to write [this forum post](https://forum.yunohost.org/t/warning-rotating-light-zero-official-app-updated-to-private-bin-all-content-will-be-cleared/3531) in a rush to get things clear for our users (some may have already upgraded...).
We'll have to handle the different instances cases in the package refactoring in order not to clear data again for people who will have already upgraded to PrivateBin. Could you have a look at this please?

**Pull request merged**
