### PR TITLE
update rainloop

### PR DESCRIPTION
**Pull request by Djip007**
bug fix and improvement:
- sso working,
- auto completion of mail suggest from ldap working
- domain autoconfig
- define admin password on install

### CODE REVIEW

**Comment by M5oul** [comment]
Thanks for that great work.

`working` status doesn't exist. You should use `ready`.

**Comment by Djip007** [comment]
I use the scripte:
> python ./add_or_update.py community.json [github url]
... may be an error in the scripte 
thanks for the correction

**Comment by Djip007** [comment]
Juste a question: the repos have change will the page https://yunohost.org/#/apps_in_progress_fr be auto-update ?

**Comment by M5oul** [comment]
Ok.

app_in_progress page will be update. Actually, It's update manually by one person.

**Comment by Djip007** [comment]
do you mean:
may be we should keep 'working' status and use 'ready' status were to make them official.
???

**Comment by M5oul** [comment]
Conceptually, it was in this goal. This doesn't means, community apps can't become official.

**Comment by Djip007** [comment]
OK!
Thanks for the "one" that make app_in_progress page update  :+1:

**Pull request merged**
