### PR TITLE
Update app's level

### PR DESCRIPTION
**Pull request by kay0u**
We really need to avoid resetting the level of an non working app (or resetting it to 0... I'm tired of doing it every week)

@maniackcrudelis @alexAubin any idea how to do that?

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
The question would be do we really need to set the level to 0 in the first place...
A not working app is not working... Whatever the level.

If we really want that.
Then, there's 2 solutions. Change the code of the CI to set level to 0 itself if the app is not working. Or modify the list of levels and set the levels to 0 for those apps

**Comment by kay0u** [comment]
Somewhere in this file: https://github.com/YunoHost/CI_package_check/blob/master/auto_build/update_level_apps.sh

**Comment by kay0u** [comment]
The thing is more that the runner shouldn't set any level for an app not tested anyway

**Comment by maniackcrudelis** [comment]
> The thing is that the runner shouldn't set any level for an app not tested anyway

It doesn't, all apps with a level have been tested. But those apps changed their status since.

**Comment by kay0u** [comment]
That's true, but since these apps have changed their status, we shouldn't rewrite their levels.

**Comment by kay0u** [comment]
What are we doing ?

**Comment by kay0u** [comment]
Can I delete the old logs of `/home/CI_package_check/logs/` in the CI if necessary?

**Comment by kay0u** [comment]
I close this PR because radicale and synapse are coming back to their level:-)

**Pull request closed without merging**
