### PR TITLE
add pixelfed

### PR DESCRIPTION
**Pull request by Jibec**
Answers https://github.com/YunoHost-Apps/pixelfed_ynh/issues/1

fixes https://github.com/YunoHost-Apps/pixelfed_ynh/issues/1

### CODE REVIEW

**Comment by Jibec** [comment]
@JimboJoe if we should not use capital letter, then I suggest to correct the whole file.

**Comment by frju365** [comment]
bon, c'est pas très très grave comme erreur. Normalement, on ne doit pas utiliser de majuscule mais bon, c'est ok si il y a une raison valable.

**Comment by frju365** [comment]
Moreover, it's alphabetical order, so it's after Pelican and not before.

**Comment by frju365** [comment]
Done.

**Pull request merged**
