### PR TITLE
Upgrade nextcloud

### PR DESCRIPTION
**Pull request by maniackcrudelis**
- [x] Complete test
- [x] Upgrade previous version
- [x] Code review
- [X] Approval (LGTM) frju365
- [x] Approval (LGTM)
- [x] CI succeeded

[Minor decision](https://github.com/YunoHost/project-organization/blob/master/yunohost_project_organization.md#minor-decision), close on 30 of june, or 26 of june.

Reference:
[Upgrade 11.0.3](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/31) *Reviewed by frju365, JimboJoe and magikcypress*
[Setup log rotation (closes #25)](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/29) *Reviewed by maniackcrudelis*

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
CI test is under waiting for now...
https://ci-apps.yunohost.org/jenkins/job/nextcloud%20(Official)/11/console

Please have a look at this PR, it's also a proposal for our PR model for all upgrade of the official app list

**Comment by JimboJoe** [comment]
I think we should state who coded the different included commits.
Then do we expect that reviewers can't be coders? In this case, @maniackcrudelis or me coded one commit, and reviewed the other one: are we legitimate to check the "code review" item? In my opinion, yes.

**Comment by JimboJoe** [comment]
I think we should move on quickly with that one now.

**Comment by JimboJoe** [comment]
At last we can merge... ;-)
Thanks everyone!

**Pull request merged**
