### PR TITLE
Update and fix Rainloop

### PR DESCRIPTION
**Pull request by scith**
- Update to 1.11.0.203
- Fix install at root: https://github.com/YunoHost-Apps/rainloop_ynh/issues/27

### CODE REVIEW

**Comment by JimboJoe** [comment]
[Standard decision](https://github.com/YunoHost/project-organization/blob/master/yunohost_project_organization_fr.md#d%C3%A9cision-standardmoyenne)
Will be closed on April 24th, or April 17th if decision anticipated.

Can be anticipated  if @scith approves his own  PR

**Comment by scith** [comment]
Github doesnt allow me to approve my own PR, but I does approve it :)

**Comment by JimboJoe** [comment]
I know you can't technically, but you can state it like you did ;-)

**Comment by JimboJoe** [comment]
Let's merge this!

**Pull request merged**
