### PR TITLE
Add peachpub

### PR DESCRIPTION
**Pull request by mhfowler**
I've been working on packaging PeachPub https://github.com/YunoHost-Apps/peachpub_ynh and the package is nearing completion. 

PeachPub is a GUI for running and managing a Scuttlebutt Pub, along with a running scuttlebutt pub. 

This has been on the yunohost apps wishlist for a long time https://yunohost.org/ar/apps_wishlist

### CODE REVIEW

**Comment by yalh76** [comment]
You must create a testing branch and merge the PR in that testing branch before merging to master ;)

**Comment by mhfowler** [comment]
@yalh76 I might be confused about something, but it seems like I don't have permission to create any new branch on the repo Yunohost/apps , and there is no branch named "testing" that I could select as a base branch for this PR. could you clarify what you mean? thank you

**Review by ericgaspar — APPROVED** [review]

**Comment by yalh76** [comment]
> @yalh76 I might be confused about something, but it seems like I don't have permission to create any new branch on the repo Yunohost/apps , and there is no branch named "testing" that I could select as a base branch for this PR. could you clarify what you mean? thank you

It's in https://github.com/YunoHost-Apps/peachpub_ynh/tree/testing, that you should create the testing branch

**Comment by mhfowler** [comment]
thanks @yalh76 , I've added a testing branch now https://github.com/YunoHost-Apps/peachpub_ynh/pull/3

**Pull request merged**
