### PR TITLE
add medusa app

### PR DESCRIPTION
**Pull request by guigot**
Hello,

this package is a copy from github.com/sickrage_ynh with corrections and modifications for Medusa.

### CODE REVIEW

**Comment by guigot** [comment]
Done.

**Comment by frju365** [comment]
Thanks ;-)

**Comment by JimboJoe** [comment]
I think it could be a good practice to systematically [ask to transfer ownership to YunoHost-Apps](https://github.com/YunoHost/apps/pull/572#issuecomment-409457232) for new apps :innocent:

**Comment by frju365** [comment]
Well, I always ask for it... but apparently I was completely tired to even see that the repos was not in the Yunohost-Apps Orga.... ://

**Pull request merged**
