### PR TITLE
Update apps.toml (iceshrimp)

### PR DESCRIPTION
**Pull request by oufmilo**

### CODE REVIEW

**Comment by alexAubin** [comment]
Hmmokay but it's not clear if it's working, I can't see any PR or tests on ci-apps-dev ... did you test it locally ? Can't we trigger a test on the dev CI before flagging it as working ?

**Comment by oufmilo** [comment]
In progress ... 😄 
https://github.com/YunoHost-Apps/iceshrimp_ynh/pull/4/

**Comment by oufmilo** [comment]
Failure because the application is not flagged as working in YunoHost's apps catalog ?

**Comment by alexAubin** [comment]
alrighty-then

**Pull request merged**
