### PR TITLE
Update Gogs revision and state

### PR DESCRIPTION
**Pull request by mbugeia**

### CODE REVIEW

**Comment by Kloadut** [comment]
Awesome! Do not hesitate to ask for an official integration if you are confident on the functionning state

**Comment by Kloadut** [comment]
This application is pure genius.

And very very good packaging, you should ask for an official integration if you are willing to maintain it :-)

**Comment by mbugeia** [comment]
Thanks, I may be a little too soon to an official integration, it seems that the install sometime fail (see https://github.com/mbugeia/gogs_ynh/issues/11). I prefer to wait for more feedback.

**Comment by stevenroose** [comment]
Pure genius, it is!

**Pull request merged**
