### PR TITLE
Update Chtickynotes - Set maintained to false + update version

### PR DESCRIPTION
**Pull request by lapineige**
This app is no longer maintained : https://github.com/YunoHost-Apps/chtickynotes_ynh/issues/7

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Why put the commit to HEAD ? Especially if no one maintain it.

**Comment by lapineige** [comment]
At least it doesn't require to do a PR to this community.json file for every (little) change ?

Even if I'll not maintain it, I might try to improve it a bit, maybe with an upgrade of the source.

**Comment by maniackcrudelis** [comment]
Using HEAD implies that the maintainer is working on a testing branch.
Otherwise, it would be better to update the commit when something concrete (and working) is done.

**Comment by lapineige** [comment]
> Using HEAD implies that the maintainer is working on a testing branch.

Oh I forgot to mention @chtixof… I wanted to ask @chtixof if it was ok to do that, and I'm ok to setup this branch if I work on the package.

**Comment by chtixof** [comment]
Thanks @lapineige for mentionning me. Do it for the best.

**Comment by lapineige** [comment]
Then @maniackcrudelis I'm fine to be working with testing + master branches.

**Comment by maniackcrudelis** [comment]
Do that means @lapineige that you're willing to take back the maintenance of this app ?

**Comment by lapineige** [comment]
No, but I may take some time to update it once.

**Comment by maniackcrudelis** [comment]
So, in that case, there's no reason to put the revision to HEAD.
An upgrade would be surely welcome, but then you just have to update the revision to the last commit when you're sure it works.

**Comment by frju365** [comment]
@lapineige : That @chtixof works on app doesn't prevent you from being maintainer too. :-) I mean that two maintainers is better than one.

**Comment by lapineige** [comment]
I don't have the time to maintain it.

**Comment by yalh76** [comment]
This PR seems out of date, maybe we can close it ?

**Comment by lapineige** [comment]
It's not out of date as the package status didn't change.

**Comment by maniackcrudelis** [comment]
As well the PR hasn't been fixed as asked.
So whether this PR is going forward, or there's no need to keep it open.

**Comment by lapineige** [comment]
Well, not using HEAD just sounds like creating unnecessary work in my opinion (open a new PR each time the package change), but it's done.

**Comment by maniackcrudelis** [comment]
Using HEAD implies the package is maintained and the maintainer is working on a testing branch.
So, the master branch is updated and made available for everyone ONLY when it's tested and it works.

Using HEAD here will made the package updated for all users at each commit, whether the commit is tested or not.

**Comment by lapineige** [comment]
And that what I'm was planning to do, not merging PR without testing it.
The package is broken anyway right now…

**Pull request merged**
