### PR TITLE
Add Gollum app

### PR DESCRIPTION
**Pull request by ketsapiwiq**
Adding app at https://github.com/ketsapiwiq/gollum_ynh. It works but it's a quick hack at packaging as I don't know how to package.
I will gladly transfer ownership to the Yunohost-Apps organization.

### CODE REVIEW

**Review by tituspijean — APPROVED** [review]
Thanks! I will invite you to the organization to transfer the repository.

**Comment by tituspijean** [comment]
I have just realized you used a 4-year-old template for Docker apps that was little-to-no used... I do not think it will work out-of-the-box, but one can hope. 🤞

**Review by ericgaspar — APPROVED** [review]

**Comment by ketsapiwiq** [comment]
Installing and removing worked on my instance, but I admit I have not tested this rigorously at all. Maybe this should be `inprogress` instead then?
It installs Docker though, I don't know if this is allowed haha. 
The template for Docker apps is not that bad actually, although yes it doesn't follow the recent guidelines on packaging for Yunohost :/

**Comment by tituspijean** [comment]
We will see soon enough how the continuous integration tests judge it. 😉

**Review by kay0u — APPROVED** [review]

**Comment by kay0u** [comment]
Please create and work on the testing branch as the revision points to HEAD

**Pull request merged**
