### PR TITLE
Remove non-free apps from community.json

### PR DESCRIPTION
**Pull request by maniackcrudelis**

### CODE REVIEW

**Comment by kay0u** [comment]
Did you check all app license one by one? :O

**Comment by maniackcrudelis** [comment]
I did... So the commit at 2 in the morning...

**Comment by Mickael-Martin** [comment]
I'm a partisan of opensource, but for me, it's a bad new. The community list not means "free".
Some devs (not professional) had work hard to add their application in Yunohost. Maybe we can create a community-nonfree list for apps non-free ?
And I didn't found any documentation about the obligation to add only free (opensource) app. Moreover, removing some apps = loosing some users or potentials users.

**Comment by maniackcrudelis** [comment]
We already have had this discussion.
The conclusion was clear, we do not include any nonfree apps into YunoHost. This decision was unanimous.

But, a nonfree list could be created and maintained by who wants. And we're ready to provide any script and help and explain how to do it.
But we're not going to do it ourselves nor maintained it or host such a list into YunoHost infra.

**Comment by liberodark** [comment]
Look the discussion : https://forum.yunohost.org/t/demande-a-la-communaute-ask-the-community/6722/8

**Comment by Psycojoker** [comment]
As stated in the discussion I'm ready to give information and directives to people that would want to create a non-free apps list, but this list won't be managed by the yunohost collective.

**Comment by Mickael-Martin** [comment]
Okay, I wasn't aware of this discussion, but it seems to me anything but unanimous....
So where are rules that distinguishes free application from non-free application in the documentation ?

**Comment by maniackcrudelis** [comment]
> but it seems to me anything but unanimous....

Unanimous regarding YunoHost devs team

**Comment by zamentur** [comment]
@Mickael-Martin The community and official list are going to disappear and merge in one.

About the point to integrate in this list proprietary apps, there was a debate on this topic https://forum.yunohost.org/t/demande-a-la-communaute-ask-the-community/6722

Sorry if you don't speak french, a big part of the discussion has been made in this language. Feel free to answer it in english if you want.

The conclusion of this discussion is:
- some proprietary apps need authorization from editors to be added in a list (and to be packaged)
- people who contributes the most in YunoHost made that to create an internet that respects its users (some proprietary soft don't and a proprietary license is a risk for users)
- YunoHost is AGPLv3 software, so one of the strongest license in libre software
- Packaging guidelines in YEP-1.3 indicates "The application lists official.json and community.json only accept packages with a free license, as well as the license for the contained application."
- Note some "free" software containing too much trackers are patched before to be integrated in the list (or could be removed, or triggered a warn message if we were not able to patch)
- Anyone is able to create **and maintain** a non-free/other list, but current contributors most involved seems to have no time and no will to do it
- it's possible to setup proprietary package with link
- we miss a mechanism to validate a license during installation

So if you want to maintain an other list with those apps, feel free to do it, all tools are in https://github.com/YunoHost/apps

**Comment by Mickael-Martin** [comment]
OK, thanks for explanations and details. I had no reference in this PR to understand why such a big decision was made so quickly.
Thanks @all

**Pull request merged**
