### PR TITLE
Enh: support for not totally free packages

### PR DESCRIPTION
**Pull request by OniriCorpe**
- rename `not-totally-free` to `not-totally-free-upstream` in `antifeatures.toml`
  - propagate this change to `apps.toml`
- create `not-totally-free-package` in `antifeatures.toml`
- description adjustment in `antifeatures.toml`
- tag the only package i know who uses a "not totally free license" (GoToSocial_ynh) in `apps.toml`
- add link to the package license in the store

> with a link to the package license

this is missing in the webadmin for the moment, see https://github.com/YunoHost/yunohost-admin/pull/545

### CODE REVIEW

**Review by alexAubin — APPROVED** [review]
LGTM but ugh there are conflicts on the .po/.mo

**Comment by OniriCorpe** [comment]
> LGTM but ugh there are conflicts on the .po/.mo

I was just solving that :"3

**Comment by OniriCorpe** [comment]
don't merge for now, it's not completely finished

**Comment by OniriCorpe** [comment]
done ^w^

**Pull request merged**
