### PR TITLE
Readme Apps - Images missing - Fix issues #1312

### PR DESCRIPTION
**Pull request by toitoinebzh**
This PR fix https://github.com/YunoHost/issues/issues/1312

### CODE REVIEW

**Comment by alexAubin** [comment]
Personally I would just choose to remove the images ... I don't think these are so useful and it's a pain to maintain in the long-term / nobody thinks about it

**Comment by toitoinebzh** [comment]
Better like this :)

**Comment by JimboJoe** [comment]
Agreed, images in that README are really not necessary in my opinion.

**Comment by maniackcrudelis** [comment]
Totally agree with that !

**Comment by toitoinebzh** [comment]
should I do something to merge this PR ? (noob inside)

**Comment by alexAubin** [comment]
Yolomergin' because there are 4 approvals :wink:

**Comment by toitoinebzh** [comment]
thank you :smile:

**Pull request merged**
