### PR TITLE
Add new app Portainer

### PR DESCRIPTION
**Pull request by aymhce**
Hello,

For me, it's working, but this app is inside a docker image.
I don't know if Yunohost CI (on LXC) is docker compatible... Can you test it please ?

Thanks

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
It doesn't work for me.
`_common: ligne 20: DOCKER_HOST : variable sans liaison`

**Comment by aymhce** [comment]
Ok I (think) fix it . It was in case you are with native yunohost. I have yunohost in docker. Can you retry please ?

**Comment by maniackcrudelis** [comment]
Same error.
You can't use `[ -z $DOCKER_HOST ]` just like that because you've used before `set -eu`. So if $DOCKER_HOST is unset, your if will be broken immediately.

You have to set this value before or to use a OR to go through the `set -eu`

**Comment by aymhce** [comment]
Thanks for help (I doesn't know set -eu ...). I think I've find a solution. Can you re-test please the last commit ?

**Comment by maniackcrudelis** [comment]
Docker failed to install
```
curl -sSL https://get.docker.com
# Executing docker install script, commit: 490beaa
Either your platform is not easily detectable or is not supported by this
installer script.
```

**Comment by aymhce** [comment]
Ok sad... What is your plateform ? Do you use lxc ?

**Comment by maniackcrudelis** [comment]
All the tests are perform in an lxc container.

**Comment by aymhce** [comment]
Ok, next week I'll work about docker integration in lxc for passing tests.

**Comment by aymhce** [comment]
hello @maniackcrudelis after a long time ago, here is a new commit ! Can you test it please ?

**Comment by maniackcrudelis** [comment]
It's all ok for me now ;)

**Pull request merged**
