### PR TITLE
Modify level

### PR DESCRIPTION
**Pull request by maniackcrudelis**

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Please take a look at https://github.com/YunoHost-Apps/zerobin_ynh/pull/16, to fix zerobin.

**Comment by JimboJoe** [comment]
I launched the CI for zerobin again; it hasn't been modified so I don't see why it failed...

**Comment by frju365** [comment]
Hi,
Can you pls wait at least one day this time before merging ?
Thanks,
frju365

**Comment by maniackcrudelis** [comment]
> I launched the CI for zerobin again; it hasn't been modified so I don't see why it failed...

Because of that !
https://github.com/YunoHost-Apps/zerobin_ynh/blob/master/scripts/install#L48-L52

If you set up this app as public, it's keep private...

**Comment by maniackcrudelis** [comment]
@frju365, it's 2 days ago, is it ok for you ?

**Pull request merged**
