### PR TITLE
Orion2036 patch 1

### PR DESCRIPTION
**Pull request by orion2036**
Please add MotionEye to Yunohost apps. This is a great video surveillance app.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
That's a great idea, but motion is not so easy to package, because you have to configure motion with a webcam. And it's really not so easy to get informations from a webcam, without an human eye.

And, the repository you point is not a YunoHost package !

**Comment by orion2036** [comment]
I am sorry for the mistakes, this is my first pull request ever :/

**Comment by maniackcrudelis** [comment]
Don't worry, there no problem.
Just explain me what do you really want to do with MotionEye.
Do you want we add it at the wishlist, or di you want to package it yourself for the community ?

**Comment by orion2036** [comment]
I want to add it to the wishlist

**Comment by maniackcrudelis** [comment]
Ok, I did it here https://github.com/YunoHost/doc/commit/90677b1ca366a534035013ceddb2dca615ed69c3

**Pull request closed without merging**
