### PR TITLE
Update app's level

### PR DESCRIPTION
**Pull request by yalh76**
- [x] [mediawiki](https://ci-apps.yunohost.org/ci/job/8985)
- [ ] [django-fmd](https://ci-apps.yunohost.org/ci/job/8986)

### CODE REVIEW

**Comment by yalh76** [comment]
@jedie, there is an issue with `django-fmd`

When you added it in apps.json, you added it as `django-find-my-device`, but in the manifest.json, it's `django-fmd`...

Which one we choose as id for the package ?

**Comment by jedie** [comment]
Hm. Sorry. In apps.json it must be the id?

**Comment by yalh76** [comment]
> Hm. Sorry. In apps.json it must be the id?

yes

so, or we change the id to `django-fmd` in apps.json or changing the id in the manifest.json and the name of the repo to `django-find-my-device`

**Comment by jedie** [comment]
> change the id to django-fmd

This sounds the best option. Don't know when I have the time to create a PR

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
