### PR TITLE
update blogotext

### PR DESCRIPTION
**Pull request by toitoinebzh**
Once this PR is accepted (https://github.com/YunoHost-Apps/blogotext_ynh/pull/4), blogotext should be working and reach level 3

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Does that mean you want to take the maintenance of this app ?

**Comment by toitoinebzh** [comment]
I can maintain it, if no one else wants to take the maintenance

**Comment by maniackcrudelis** [comment]
This app is set as unmaintained, and you're changing it to maintained.
So that means for me that you're willing to.

**Comment by toitoinebzh** [comment]
well, yes I willing to take the maintenance.

**Comment by maniackcrudelis** [comment]
I give you permissions on this repo then.

**Comment by toitoinebzh** [comment]
thank you, blogotext has now been updated

**Pull request merged**
