### PR TITLE
DokuWiki : Refactoring and upgrade to latest version

### PR DESCRIPTION
**Pull request by JimboJoe**
Following [this PR](https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/23) by @magikcypress (thanks!):
* Major upgrade of DokuWiki version
* Package refactored to adjust to latest standards
* Level 7 in package_check

EDIT : Adding this [small PR](https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/24) to the decision.

[Standard decision](https://github.com/YunoHost/project-organization/blob/master/yunohost_project_organization_fr.md#d%C3%A9cision-standardmoyenne)
Will be closed on April 29th, or April 22th if decision anticipated.

### CODE REVIEW

**Comment by magikcypress** [comment]
I think it's good ! ;)

**Comment by JimboJoe** [comment]
I also approve (Can't formally approve as I'm the PR creator)

**Comment by alexAubin** [comment]
(Bump?)

**Comment by JimboJoe** [comment]
Latest things are happening [here](https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/28).

**Comment by magikcypress** [comment]
Sorry for the delay! If you want to test! ;)

**Comment by JimboJoe** [comment]
The [fix PR](https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/28) has been merged, we can now move on with the review process (at last ;-)
@zamentur, are you OK now?

**Comment by zamentur** [comment]
5 contributors have reviewed I think we can merge. I put the ready to merge status and we merge soon.

**Comment by maniackcrudelis** [comment]
Ok for me ;)

**Comment by JimboJoe** [comment]
I wanted to merge all the way, but one travis-ci test doesn't pass... but I don't understand what this test is :confused:

**Pull request merged**
