### PR TITLE
Remove spip2, upstream unmaintained, people should move to spip 3...

### PR DESCRIPTION
**Pull request by alexAubin**
Follow-up of https://github.com/YunoHost/doc/pull/943

- SPIP 2 upstream ain't maintained anymore
- The yunohost app neither
- There might be security risks involved in using SPIP2 ...

To be discussed

### CODE REVIEW

**Comment by kay0u** [comment]
Maybe we should normalize the SPIP package, reach level 7 with it, and then remove SPIP2?

**Comment by brunob** [comment]
FTR, SPIP 3.2 is the latest stable version available, and SPIP 3.0 support will end on 30 june 2019 cf https://www.mail-archive.com/spip-dev@rezo.net/msg66764.html

**Comment by kay0u** [comment]
Just to let you know, I'm working on SPIP.

**Comment by kay0u** [comment]
New PR: https://github.com/YunoHost-Apps/spip_ynh/pull/4

Have to test with package_check

**Comment by kay0u** [comment]
Job is done, I'm not against a review if it's possible: https://github.com/YunoHost-Apps/spip_ynh/pull/4

Moreover, if someone can explain to me how I can migrate spip2 to this app, it would be great!

**Comment by maniackcrudelis** [comment]
For the "YunoHost" part of the migration, you can have a look to this experimental helper: https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_handle_app_migration/ynh_handle_app_migration

**Comment by maniackcrudelis** [comment]
@kay0u are you done with spip3 ?

**Comment by kay0u** [comment]
Not yet. In fact, we have a problem with generating archives on the spip server. The sha256sum changes every day. I have to copy/paste the source code into the YNH project to make sure we have the right version.

I'll do it soon.

**Comment by yalh76** [comment]
> 
> 
> Not yet. In fact, we have a problem with generating archives on the spip server. The sha256sum changes every day. I have to copy/paste the source code into the YNH project to make sure we have the right version.
> 
> I'll do it soon.

Adding sources in the ynh package can make git pull very slow

Maybe,

1. you can use the GitHub Release system that let you upload a file
or
2. you can ask @zamentur an access to https://build.yunohost.org/apps/ ( it the way wekan_ynh is managed)

https://github.com/YunoHost-Apps/wekan_ynh/blob/2871d37c8bec72548955cd1f7d4546e29876a9c3/conf/app.src#L3

**Comment by maniackcrudelis** [comment]
Indeed, You changed the checksum 7 days ago, the timestamp of the archive is from 21-01-2019 15:20, and still the checksum isn't good anymore...
That's crazy...

**Comment by maniackcrudelis** [comment]
Feel free to merge @kay0u when it's ok for you.

**Comment by kay0u** [comment]
Level 7, merging!

**Pull request merged**
