### PR TITLE
Update Mediawiki CI level

### PR DESCRIPTION
**Pull request by Salamandar**
Mediawiki passed level 7 on CI. If I understand everything correctly, I have to do a MR here :)

### CODE REVIEW

**Comment by yalh76** [comment]
You don't need to update the CI level.
CI level is automatically updated each friday ;)

But thanks for the work on mediawiki ^^

**Comment by Salamandar** [comment]
Thanks for the info. Couldn't find it anywhere :'(

**Comment by yalh76** [comment]
There's a weekly update from https://ci-apps.yunohost.org/ci/ results :)

**Comment by Salamandar** [comment]
Okay, I understand :)
That would be great to add this info to the Readme (or the yunohost dev docs) because I didn't understand why the results from ci-apps.yunohost.org didn't automatically update this repo… ;)

**Comment by yalh76** [comment]
I agree... but I do't where in the documentation, we can put that information....

**Pull request closed without merging**
