### PR TITLE
add octoprint (not working yet)

### PR DESCRIPTION
**Pull request by Gredin67**

### CODE REVIEW

**Comment by Gredin67** [comment]
https://github.com/YunoHost/apps/pull/1891
https://github.com/Tropicao/octoprint_ynh/issues/3
and other issues

**Comment by Gredin67** [comment]
@alexAubin @ericgaspar @tituspijean can you add @Tropicao to the YunoHost-Apps orga so he can keep control on the https://github.com/Tropicao/octoprint_ynh repo after transferring it ? Can you also give me access rights so I can contribute if @Tropicao agrees ?

- Confirm app is self-hostable and generally makes sense to possibly integrate in YunoHost : Multi-instance can be deployed on debian, see https://github.com/paukstelis/octoprint_deploy Can be used in combination with Home-Assistant to use/monitor 3D printers from remote https://github.com/cmroche/OctoPrint-HomeAssistant

- Confirm app's license is opensource/free software (or not-totally-free, case by case TBD) : AGPL-3.0 license

- Description describes concisely what the app is/does : OctoPrint provides a snappy web interface for controlling consumer 3D printers https://github.com/OctoPrint/OctoPrint

**Comment by Tagadda** [comment]
Hey @Tropicao, you've got an invite !
Once you accept it, you'll be able to transfer your repository to the YunoHost-Apps organization.
And once it got transferred, I'll be able to give write access to you @Gredin67 :)
Feel free to ping me here once it's done !

**Comment by Tropicao** [comment]
@Tagadda sorry for the late reply, I finally got time to accept your invite and proceed with the transfer :+1:

**Review by Tagadda — APPROVED** [review]

**Pull request merged**
