### PR TITLE
remove Huginn app

### PR DESCRIPTION
**Pull request by onde2rock**
Not working for a long time and i won't fix.

### CODE REVIEW

**Comment by frju365** [comment]
Could You please transfer the ownership to the Yunohost-Apps repository to let other dev contributing on it ?

**Comment by frju365** [comment]
I sent you an invitation you must accept to add repos on Yunohost-Apps orga.

**Comment by onde2rock** [comment]
Ok, it's done

**Comment by frju365** [comment]
can You transfer the ownership of huginn_ynh to the Yunohost-Apps repos now ?

**Comment by frju365** [comment]
have you accepted the invitation to the Yunohost-Apps organization ?

**Comment by onde2rock** [comment]
Oh that's why ! 
No I didn't receive the invitation.

**Comment by frju365** [comment]
You didn't receive the invitation ?

**Comment by onde2rock** [comment]
I didn't receive the invitation.

**Comment by frju365** [comment]
ok. Normally, I resend you an invitation just now. :) Srry.

**Comment by frju365** [comment]
could you pls check again your mails ?

**Comment by frju365** [comment]
or you can visit https://github.com/YunoHost-Apps too to accept the invitation.

**Comment by onde2rock** [comment]
transfer done !

**Comment by frju365** [comment]
Thanks ;) 
(Then I close the PR... other dev will maintain the app if you can't-- The App groupd will check it--- You have still right access on your repos)

**Comment by onde2rock** [comment]
ok thanks
closing

**Pull request closed without merging**
