### PR TITLE
schemas: Add schemas for apps.toml and categories.toml

### PR DESCRIPTION
**Pull request by Salamandar**
Eh, I don't really know if they could be useful. Maybe in github merge requests checks ?
But well, they were easy to write.

### CODE REVIEW

**Comment by alexAubin** [comment]
Hmmmyes indeed it would be pretty cool to have a github action with this check (there's already one but only checks that it's a valid toml and that there's consistency in the url : https://github.com/YunoHost/apps/blob/master/.github/workflows/main.yml#L21 )

**Comment by Salamandar** [comment]
I think that json-schema can even incorporate some custom logic that can replace the catalog_linter.py (but is it what we want ?)

**Comment by alexAubin** [comment]
I'm re-reading the catalog linter and it's only for : 
- checking the url of the app ends with `{app_id}_ynh` for consistency
- that the `category` info exists and is effectively defined in `categories.yml`

not sure if all of this can be done using the schema but it would be nice, maybe checking that the category exists in `categories.yml` is not really mandatory

**Comment by Salamandar** [comment]
Actually this was more advance in my memory than it is really, so, we can check it's `.*_ynh` but not `{app}_ynh`, so the catalog linter is still useful… by the way i'm rewriting it :D

**Pull request merged**
