### PR TITLE
Make rainloop_ynh official

### PR DESCRIPTION
**Pull request by polytan02**
- [x] Package_check has no error anymore.
- [x] @scith made lots of work to integrate ldap and sso so level 4 can be checked manually
- [x] Once level 4 validated, the app should be level 7 automatically
- [x] Make the app multi instances

### CODE REVIEW

**Comment by polytan02** [comment]
I added a commit to remove from community.
The package_linter is OK to me once the "issue" are looked in details, no ?

**Comment by polytan02** [comment]
@M5oul many thanks ofr your comments, these need to be addressed.

**Comment by polytan02** [comment]
Latest comments have been taken into account.

**Comment by alexAubin** [comment]
This is slightly off-topic, but is there any reason to prefer roundcube over rainloop ? Imho rainloop is much more modern in terms of UI. And also seems lightweight compared to roundcube (I recently had a failed install of roundcube because of composer not having enough memory). (Don't know much about how rainloop works though)

Looking forward to having rainloop as official !

**Comment by maniackcrudelis** [comment]
I've started to review the code.

- [YEP 1.3](https://github.com/YunoHost/doc/blob/master/packaging_apps_guidelines_fr.md#yep-13---indiquer-la-licence-associ%C3%A9e-au-paquet---brouillon--auto--working-): The license is still at 'free' into the manifest.
- As you said, the hook files do not work with a multi-instance installation. But, these are only demanded for the level 8. So it's ok.
- https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/scripts/install#L152-L153, why ? If these reloads failed, it shall failed the installation.
Same thing for upgrade and restore script.
- I'm really not agree with `set -eu` in the remove script. And we have a perfect exemple here. Look at the log of CI, the remove script encountered an error with the suppression of the PGP key. And, if you look at the complete log, you might seeing that the remove script stop after this fail. So, because you use `set -eu`, the script didn't ended correctly.
In this case, it's better to secure your `rm -rf` instead of use `set -eu`. But, it's a globally problem...
- https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/scripts/upgrade#L15, not really a problem, but you should use `trap '' ERR`
- Have you check an upgrade from an old version of rainloop?

**Comment by polytan02** [comment]
Hi @maniackcrudelis 

We have taken into account your comments and committed a few changes :  
- [x] License : https://github.com/YunoHost-Apps/rainloop_ynh/commit/4b3654175dc23ebf5ddb6bf2d27ac434b3e967d7
- [x] No need of || true after service reload https://github.com/YunoHost-Apps/rainloop_ynh/commit/7ac0353c8e7724456c2aba9ae2a2a3b1f36cfbe7
- [x] No set -eu in remove script https://github.com/YunoHost-Apps/rainloop_ynh/commit/55eaed29721d1626ce9931efe0553282d4782507
- [x] Use of trap '' ERR https://github.com/YunoHost-Apps/rainloop_ynh/commit/e7f0cd37a983961277fb2749f2cbb863605757c9

Also, we have done the extra bits : 
- [x] use of .fonctions and simplification of some part of the code https://github.com/YunoHost-Apps/rainloop_ynh/commit/5d0e31beb352a4629f443c0cd9c1f61f762100e5
- [x] Place rainloop_version in sources folder for easier maintenance https://github.com/YunoHost-Apps/rainloop_ynh/commit/add5d2f2f07be1dd9c24472696fbe9cf57813519

**Comment by polytan02** [comment]
- [x] Rainloop license is actually AGPL-3.0 https://github.com/YunoHost-Apps/rainloop_ynh/commit/b2d0e25836f12c7343164129e7f58ec8eb27eeac
- [x] Use of secure remove https://github.com/YunoHost-Apps/rainloop_ynh/commit/3257e543a2135fcf278229ae845361eeccd45e36

**Comment by polytan02** [comment]
- [x] GPL-3.0 for the package (not to be missunderstood by the AGPL-3.0 of rainloop) https://github.com/YunoHost-Apps/rainloop_ynh/commit/3dbf9135a28155dfa9c90354b4094c4e76724408

**Comment by polytan02** [comment]
@M5oul I should now have fixes package_linter

**Comment by scith** [comment]
Sorry I can't review this extensively at the moment, but I discussed with polytan02 as he made his changes so I suppose everything is OK

**Comment by maniackcrudelis** [comment]
Just one things left @polytan02 :

> "Have you check an upgrade from an old version of rainloop?"

**Comment by polytan02** [comment]
@maniackcrudelis I have just tested the upgrade from existing rainloop (from latest community version) and it worked fine.

One annoying bug remains : https://github.com/YunoHost-Apps/rainloop_ynh/issues/24 
==> Should we cancel the "official" request because of this ?

**Comment by maniackcrudelis** [comment]
> ==> Should we cancel the "official" request because of this ?

No, all it's ok for me.
I pass this decision at a standard decision. So the end-date is fixed to the 19th of march, or 12th if it's anticipated. We need 5 reviews (7 for anticipate)

**Comment by polytan02** [comment]
Well, it seems that there is a plugin done by a yunohost member which, once activated, solve the bug, so even better !

https://github.com/YunoHost-Apps/rainloop_ynh/tree/master/sources/plugins/ynh-login-mapping

I don't really know how to activate it, maybe @scith know ?

**Comment by JimboJoe** [comment]
@polytan02  Seems that you have to add the plugin name to the `plugins` variable here: https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/scripts/install#L83

**Comment by scith** [comment]
I had an old version of rainloop app on my VM. I tried the upgrade and it worked :+1:

**Comment by polytan02** [comment]
I really would like to sort out the login ! = email bug.

**Comment by scith** [comment]
Let's discuss it more on the issue then https://github.com/YunoHost-Apps/rainloop_ynh/issues/24

**Comment by scith** [comment]
Issue fixed in the last commit
Is everything good to make the app official now?

**Comment by M5oul** [comment]
You must squash into one commit.
And remove the app from community list.

**Comment by polytan02** [comment]
@M5oul what is squash ?

**Comment by M5oul** [comment]
`git squash` is to join many commits into one.
A `git rebase --interative` is necessary.
I could do it.

**Comment by polytan02** [comment]
@M5oul yes, please proceed. I don't want to break everything :)

**Comment by M5oul** [comment]
I didn't succeed to squashed easilly.
So, I pushed on a new branch](https://github.com/YunoHost/apps/commit/162e61675a4d].
It could be merge if you are ok.

**Comment by M5oul** [comment]
Done with https://github.com/YunoHost/apps/commit/162e61675a4d5e82c9042e422c880c79e565fd05.

**Comment by scith** [comment]
Yay, congrats all :champagne:

**Comment by maniackcrudelis** [comment]
> standard decision. So the end-date is fixed to the 19th of march, or 12th if it's anticipated. We need 5 reviews (7 for anticipate)

...

**Comment by scith** [comment]
Ah oui OK c'est pas très standard donc d'anticiper avec 3 reviewers ...
On à qu'à dire qu'on fera le communiqué d'annonce qu'une fois toutes les reviews collectées ? :)
En tout cas si vous voyez des choses à dix entre temps hésitez pas

**Pull request closed without merging**
